export const LOG_EVENTS = {
  authLoginSuccess: "AUTH_LOGIN_SUCCESS",
  authLoginFailure: "AUTH_LOGIN_FAILURE",
  authAccessDenied: "AUTH_ACCESS_DENIED",

  adminInspectorCreateSuccess: "ADMIN_INSPECTOR_CREATE_SUCCESS",
  adminInspectorCreateFailure: "ADMIN_INSPECTOR_CREATE_FAILURE",
  adminInspectorDeleteSuccess: "ADMIN_INSPECTOR_DELETE_SUCCESS",
  adminInspectorDeleteFailure: "ADMIN_INSPECTOR_DELETE_FAILURE",
  adminInspectorRoleUpdateSuccess: "ADMIN_INSPECTOR_ROLE_UPDATE_SUCCESS",
  adminInspectorRoleUpdateFailure: "ADMIN_INSPECTOR_ROLE_UPDATE_FAILURE",

  adminFormCategoryCreateSuccess: "ADMIN_FORM_CATEGORY_CREATE_SUCCESS",
  adminFormCategoryCreateFailure: "ADMIN_FORM_CATEGORY_CREATE_FAILURE",
  adminFormCategoryUpdateSuccess: "ADMIN_FORM_CATEGORY_UPDATE_SUCCESS",
  adminFormCategoryUpdateFailure: "ADMIN_FORM_CATEGORY_UPDATE_FAILURE",
  adminFormCategoryReorderSuccess: "ADMIN_FORM_CATEGORY_REORDER_SUCCESS",
  adminFormCategoryReorderFailure: "ADMIN_FORM_CATEGORY_REORDER_FAILURE",
  adminFormCategoryDeleteSuccess: "ADMIN_FORM_CATEGORY_DELETE_SUCCESS",
  adminFormCategoryDeleteFailure: "ADMIN_FORM_CATEGORY_DELETE_FAILURE",
  adminFormCategoryDeleteBlockedActiveCriteria: "ADMIN_FORM_CATEGORY_DELETE_BLOCKED_ACTIVE_CRITERIA",

  adminFormCriterionCreateSuccess: "ADMIN_FORM_CRITERION_CREATE_SUCCESS",
  adminFormCriterionCreateFailure: "ADMIN_FORM_CRITERION_CREATE_FAILURE",
  adminFormCriterionUpdateSuccess: "ADMIN_FORM_CRITERION_UPDATE_SUCCESS",
  adminFormCriterionUpdateFailure: "ADMIN_FORM_CRITERION_UPDATE_FAILURE",
  adminFormCriterionReorderSuccess: "ADMIN_FORM_CRITERION_REORDER_SUCCESS",
  adminFormCriterionReorderFailure: "ADMIN_FORM_CRITERION_REORDER_FAILURE",
  adminFormCriterionMoveSuccess: "ADMIN_FORM_CRITERION_MOVE_SUCCESS",
  adminFormCriterionMoveFailure: "ADMIN_FORM_CRITERION_MOVE_FAILURE",
  adminFormCriterionSoftRemoveSuccess: "ADMIN_FORM_CRITERION_SOFT_REMOVE_SUCCESS",
  adminFormCriterionSoftRemoveFailure: "ADMIN_FORM_CRITERION_SOFT_REMOVE_FAILURE",
  adminFormCriterionRestoreSuccess: "ADMIN_FORM_CRITERION_RESTORE_SUCCESS",
  adminFormCriterionRestoreFailure: "ADMIN_FORM_CRITERION_RESTORE_FAILURE",
  adminFormCriterionHardDeleteSuccess: "ADMIN_FORM_CRITERION_HARD_DELETE_SUCCESS",
  adminFormCriterionHardDeleteFailure: "ADMIN_FORM_CRITERION_HARD_DELETE_FAILURE",
  adminFormCriterionHardDeleteBlockedHasAnswers: "ADMIN_FORM_CRITERION_HARD_DELETE_BLOCKED_HAS_ANSWERS",

  auditCreateSuccess: "AUDIT_CREATE_SUCCESS",
  auditCreateFailure: "AUDIT_CREATE_FAILURE",
  auditUpdateSuccess: "AUDIT_UPDATE_SUCCESS",
  auditUpdateFailure: "AUDIT_UPDATE_FAILURE",

  auditExportDocxFailure: "AUDIT_EXPORT_DOCX_FAILURE",
  clientException: "CLIENT_EXCEPTION",
  serverException: "SERVER_EXCEPTION",
} as const
